### ISSUE TITLE
API Suggestion: Replace/remove all "unsafe" toNonEmptyFoo extensions and rename the nullable ones

### ISSUE THREAD

**Issue by ragnese** [quickbirdstudios/NonEmptyCollections#3]
For example, you have:

```
fun <T> List<T>.nonEmptyOrNull() = if (isEmpty()) null else toNonEmptyList()
```

and

```
@UnsafeNonEmptyCollectionApi
fun <T> Iterable<T>.toNonEmptyList(): NonEmptyList<T> = isAlreadyNonEmptyOr {
    nonEmptyListOf(first(), drop(1))
}
```

If it were me, I'd probably be lazy and just drop the whole unsafe set. The user can always just do:
```
val nonEmpty = someList.nonEmptyOrNull() ?: error("Bug! I expected this to be non-empty!")
```

But if you keep both APIs, I suggest at least naming both sets with the "toNonEmptyFoo" style. A lot of methods in the Kotlin standard library have names like `toList`, so going with `toNonEmptyList` seems like a good match.

**Comment by balazstothofficial** [comment]
Good point 👍🏻 
Please have a look at: https://github.com/quickbirdstudios/NonEmptyCollections/pull/4

**Comment by ragnese** [comment]
I like it 👍
