### ISSUE TITLE
NonEmptyCollection should use out param to match Collection

### ISSUE THREAD

**Issue by ragnese** [quickbirdstudios/NonEmptyCollections#8]
i.e., `interface NonEmptyCollection<out T>: Collection<T>` because `Collection` is defined as `interface Collection<out T>`.

Then NonEmptyList, NonEmptySet, NonEmptyMap should also use out params.

**Comment by balazstothofficial** [comment]
Please have a look at https://github.com/quickbirdstudios/NonEmptyCollections/pull/10
